### ISSUE TITLE
The updater seems to throw an error about the scheduler. There's a chain of exceptions in the update script.

### ISSUE THREAD

**Issue by jabrouwer82** [jabrouwer82/manga-notifier#28]
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 267, in Handle
    result = handler(dict(self._environ), self._StartResponse)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1519, in __call__
    response = self._internal_error(e)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in **call**
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in **call**
    return handler.dispatch()
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/apps/s~ballin-octo-wallhack/1-8-2.383293096932827840/utils.py", line 30, in handle_exception
    webapp2.RequestHandler.handle_exception(self, exception, debug_mode)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(_args, *_kwargs)
  File "/base/data/home/apps/s~ballin-octo-wallhack/1-8-2.383293096932827840/update.py", line 80, in get
    Schedule.schedule()
AttributeError: type object 'Schedule' has no attribute 'schedule'

**Comment by jabrouwer82** [comment]
local variable 'prev_update_is_new' referenced before assignment
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1511, in **call**
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in **call**
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in **call**
    return handler.dispatch()
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/apps/s~ballin-octo-wallhack/1-8-3.383298654500360806/utils.py", line 30, in handle_exception
    webapp2.RequestHandler.handle_exception(self, exception, debug_mode)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(_args, *_kwargs)
  File "/base/data/home/apps/s~ballin-octo-wallhack/1-8-3.383298654500360806/update.py", line 80, in get
    Schedule.schedule_update()
  File "/base/data/home/apps/s~ballin-octo-wallhack/1-8-3.383298654500360806/schedule.py", line 44, in schedule_update
    if not prev_update_is_new:
UnboundLocalError: local variable 'prev_update_is_new' referenced before assignment

**Comment by jabrouwer82** [comment]
Getting there.
local variable 'countdown' referenced before assignment
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1511, in **call**
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in **call**
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in **call**
    return handler.dispatch()
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/apps/s~ballin-octo-wallhack/1-8-3.383298707783511003/utils.py", line 30, in handle_exception
    webapp2.RequestHandler.handle_exception(self, exception, debug_mode)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(_args, *_kwargs)
  File "/base/data/home/apps/s~ballin-octo-wallhack/1-8-3.383298707783511003/update.py", line 84, in get
    self.update(manga)
  File "/base/data/home/apps/s~ballin-octo-wallhack/1-8-3.383298707783511003/update.py", line 55, in update
    manga.countdown += countdown
UnboundLocalError: local variable 'countdown' referenced before assignment

**Comment by jabrouwer82** [comment]
Not quite done with this yet.
unsupported operand type(s) for +=: 'NoneType' and 'float'
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1511, in **call**
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in **call**
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in **call**
    return handler.dispatch()
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/apps/s~ballin-octo-wallhack/1-8-3.383298803245957056/utils.py", line 30, in handle_exception
    webapp2.RequestHandler.handle_exception(self, exception, debug_mode)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(_args, *_kwargs)
  File "/base/data/home/apps/s~ballin-octo-wallhack/1-8-3.383298803245957056/update.py", line 88, in get
    self.update(manga)
  File "/base/data/home/apps/s~ballin-octo-wallhack/1-8-3.383298803245957056/update.py", line 59, in update
    manga.countdown += countdown
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'float'
